export const SHOW_ADD_EVENT_SCHEDULE_MODAL = 'SHOW_ADD_EVENT_SCHEDULE_MODAL';
export const SHOW_EDIT_EVENT_SCHEDULE_MODAL = 'SHOW_EDIT_EVENT_SCHEDULE_MODAL';
export const SHOW_DELETE_EVENT_SCHEDULE_MODAL = 'SHOW_DELETE_EVENT_SCHEDULE_MODAL';
export const SET_DELETE_MULTIPLE_SCHEDULE_MODAL = 'SET_DELETE_MULTIPLE_SCHEDULE_MODAL';
