export const POWER_SECTION = 'POWER_SECTION';
export const EMOJI_SECTION = 'EMOJI_SECTION';
export const OVERLAY_SECTION = 'OVERLAY_SECTION';
export const CONFIGURATIONS = 'CONFIGURATIONS';
export const OFFLINE_IMAGE = 'OFFLINE_IMAGE';
