export const SET_HABITAT = 'SET_HABITAT';
export const UNSET_HABITAT = 'UNSET_HABITAT';
export const SET_HABITAT_LIKED = 'SET_HABITAT_LIKED';
export const SET_HABITAT_PROPS = 'SET_HABITAT_PROPS';
export const SET_HABITAT_STREAM_STARTED = 'SET_HABITAT_STREAM_STARTED';
