export const SET_MAP_DATA = 'SET_MAP_DATA';
export const SELECT_HABITAT = 'SELECT_HABITAT';
export const UPDATE_HABITAT_DATA = 'UPDATE_HABITAT_DATA';
export const TOGGLE_MAP_MODAL = 'TOGGLE_MAP_MODAL';
export const SELECT_EDIT_HABITAT = 'SELECT_EDIT_HABITAT';
export const UPDATE_HABITAT_LIST = 'UPDATE_HABITAT_LIST';
