// opening in Grommet Layer
export const OPEN_MODAL_CARDS = 'OPEN_MODAL_CARDS';
export const CLOSE_MODAL_CARDS = 'CLOSE_MODAL_CARDS';

export const MOBILE_CARD_INDEX_NEXT = 'MOBILE_CARD_INDEX_NEXT';
export const MOBILE_CARD_INDEX_PREV = 'MOBILE_CARD_INDEX_PREV';
export const MOBILE_CARD_INDEX_RESET = 'MOBILE_CARD_INDEX_RESET';

// opening in Grommet Layer
export const OPEN_MODAL_CALENDAR = 'OPEN_MODAL_CALENDAR';
export const CLOSE_MODAL_CALENDAR = 'CLOSE_MODAL_CALENDAR';
export const OPEN_MODAL_QUESTIONS_AND_ANSWERS = 'OPEN_MODAL_QUESTIONS_AND_ANSWERS';
export const CLOSE_MODAL_QUESTIONS_AND_ANSWERS = 'CLOSE_MODAL_QUESTIONS_AND_ANSWERS';
